export default {
  LOAD_USER_LIST: 'LOAD_USER_LIST',
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  LOAD_PER_LIST: 'LOAD_PER_LIST',
  ADD_PER: 'ADD_PER',
  EDIT_PER: 'EDIT_PER',
  DELETE_PER_IDS: 'DELETE_PER_IDS',
};
